/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phase3;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author DELL
 */
public class OrgMainPage extends javax.swing.JFrame {
    Organization[] organization = new Organization[30];
    Campaign[] campaign = new Campaign[20];
    int countCampaign = 0;
    int countOrg = 0;
    String campaignDetail = "";
    Connection myConn;
    PreparedStatement pst;
    Statement myStat;
    ResultSet myRs;
    int id;
    String orgName;
    String orgAddress;
    String orgPhoneNo;
    String orgEmail;
    /**
     * Creates new form OrgMainPage
     */
    public OrgMainPage() {
        initComponents();
        showCamTable();
        txtCamID.setEditable(false);
        txtOrgID.setEditable(false);
        txtOrgName.setEditable(false);
        txtOrgAddress.setEditable(false);
        txtOrgPhoneNo.setEditable(false);
        txtOrgEmail.setEditable(false);
        Toolkit toolkit = getToolkit(); //center jFrame
        Dimension size = toolkit.getScreenSize(); //center jFrame
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2); //center jFrame
         getID();
         getCamID();
    }



public ArrayList<Campaign> jTable2(){
    ArrayList<Campaign> jTable2 = new ArrayList<>();
    try{
        myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
        String sql = "SELECT id,campaignName,campaignStartDate, campaignVenue FROM `campaign`";
        myStat = myConn.createStatement();
        myRs = myStat.executeQuery(sql);
        Campaign cam;
        while(myRs.next()){
            cam = new Campaign(myRs.getInt("id"),myRs.getString("campaignName"), myRs.getString("campaignStartDate"), myRs.getString("campaignVenue"));
            jTable2.add(cam);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    return jTable2;
}

public void showCamTable(){
     ArrayList<Campaign> list = jTable2();
     DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
     Object[] row = new Object[4];
     for(int i=0;i <list.size();i++){
    row[0] = list.get(i).getId();
    row[1] = list.get(i).getCampaignName();
    row[2] = list.get(i).getCampaignStartDate();
    row[3] = list.get(i).getCampaignVenue();
    model.addRow(row);
}
}

public void getID(){
 try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
            String value1 = txtOrgID.getText();
            String sql = "SELECT `id`,  `orgName`,  `orgAddress`, `orgPhoneNo`,`orgEmail` FROM `organization`"; 
            myStat = myConn.createStatement();
            ResultSet rs = myStat.executeQuery(sql);
            while(rs.next()){
                id = rs.getInt("id");
                orgName = rs.getString("orgName");
                orgAddress = rs.getString("orgAddress");
                orgPhoneNo= rs.getString("orgPhoneNo");
                orgEmail= rs.getString("orgEmail");
                txtOrgID.setText(Integer.toString(id));    
                txtOrgName.setText(orgName);
                txtOrgAddress.setText(orgAddress);
                txtOrgPhoneNo.setText(orgPhoneNo);
                txtOrgEmail.setText(orgEmail);
        
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
                    }
}

public void getCamID(){
 try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
            String value1 = txtOrgID.getText();
            String sql = " SELECT `id` FROM `campaign`"; 
            myStat = myConn.createStatement();
            ResultSet rs = myStat.executeQuery(sql);
            while(rs.next()){
                id = rs.getInt("id");
               id++;
               txtCamID.setText(Integer.toString(id));    
                
        
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,e);
                    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pblOrgInput = new javax.swing.JPanel();
        lblOrgHeader = new javax.swing.JLabel();
        lblOrgName = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        txtOrgAddress = new javax.swing.JTextField();
        lblOrgAddress = new javax.swing.JLabel();
        lblOrgPhoneNo = new javax.swing.JLabel();
        txtOrgPhoneNo = new javax.swing.JTextField();
        lblOrgEmail = new javax.swing.JLabel();
        txtOrgEmail = new javax.swing.JTextField();
        btnOrgSubmitButton = new javax.swing.JButton();
        checkBoxUOrgUpdate = new javax.swing.JCheckBox();
        lblOrgID1 = new javax.swing.JLabel();
        txtOrgID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pnlCampaignInput = new javax.swing.JPanel();
        lblCampaignHeader = new javax.swing.JLabel();
        lblCampaignName = new javax.swing.JLabel();
        txtCampaignName = new javax.swing.JTextField();
        lblCampaignStartDate = new javax.swing.JLabel();
        lblCampaignVenue = new javax.swing.JLabel();
        txtCampainVenue = new javax.swing.JTextField();
        btnCampaignSubmitButton = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cmpUpdate = new javax.swing.JCheckBox();
        lblOrgID2 = new javax.swing.JLabel();
        txtCamID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Campaign Name", "Campaign Start Date", "Campaign Venue"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        lblOrgHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrgHeader.setText("Organization Information");

        lblOrgName.setText("Organization Name : ");

        lblOrgAddress.setText("Organization Address : ");

        lblOrgPhoneNo.setText("Organization Phone Number: ");

        lblOrgEmail.setText("Organization Email : ");

        btnOrgSubmitButton.setText("Submit");
        btnOrgSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgSubmitButtonActionPerformed(evt);
            }
        });

        checkBoxUOrgUpdate.setText("Update?");
        checkBoxUOrgUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUOrgUpdateActionPerformed(evt);
            }
        });

        lblOrgID1.setText("Organization ID : ");

        txtOrgID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrgIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pblOrgInputLayout = new javax.swing.GroupLayout(pblOrgInput);
        pblOrgInput.setLayout(pblOrgInputLayout);
        pblOrgInputLayout.setHorizontalGroup(
            pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblOrgInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblOrgInputLayout.createSequentialGroup()
                        .addComponent(checkBoxUOrgUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrgSubmitButton))
                    .addGroup(pblOrgInputLayout.createSequentialGroup()
                        .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pblOrgInputLayout.createSequentialGroup()
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOrgName)
                                    .addComponent(lblOrgAddress)
                                    .addComponent(lblOrgPhoneNo)
                                    .addComponent(lblOrgEmail))
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pblOrgInputLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOrgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOrgID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblOrgInputLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtOrgAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOrgPhoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblOrgHeader)
                            .addComponent(lblOrgID1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pblOrgInputLayout.setVerticalGroup(
            pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblOrgInputLayout.createSequentialGroup()
                .addComponent(lblOrgHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrgID1)
                    .addComponent(txtOrgID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrgName)
                    .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrgAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrgAddress))
                .addGap(22, 22, 22)
                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrgPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrgPhoneNo))
                .addGap(18, 18, 18)
                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrgEmail))
                .addGap(18, 18, 18)
                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxUOrgUpdate)
                    .addComponent(btnOrgSubmitButton))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Campaign Information List");

        lblCampaignHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCampaignHeader.setText("Campaign Information");

        lblCampaignName.setText("Campaign Name : ");

        lblCampaignStartDate.setText("Campaign Start Date  : ");

        lblCampaignVenue.setText("Campaign Venue : ");

        btnCampaignSubmitButton.setText("Submit");
        btnCampaignSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampaignSubmitButtonActionPerformed(evt);
            }
        });

        cmpUpdate.setText("Update?");
        cmpUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpUpdateActionPerformed(evt);
            }
        });

        lblOrgID2.setText("Campaign ID : ");

        txtCamID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCampaignInputLayout = new javax.swing.GroupLayout(pnlCampaignInput);
        pnlCampaignInput.setLayout(pnlCampaignInputLayout);
        pnlCampaignInputLayout.setHorizontalGroup(
            pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                        .addComponent(lblOrgID2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCamID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                        .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCampaignName)
                                    .addComponent(lblCampaignStartDate)
                                    .addComponent(lblCampaignVenue)
                                    .addComponent(cmpUpdate))
                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCampaignInputLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCampainVenue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnCampaignSubmitButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCampaignName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblCampaignHeader))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCampaignInputLayout.setVerticalGroup(
            pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                .addComponent(lblCampaignHeader)
                .addGap(14, 14, 14)
                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrgID2)
                    .addComponent(txtCamID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaignName)
                    .addComponent(txtCampaignName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCampaignStartDate)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCampainVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCampaignVenue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCampaignSubmitButton)
                    .addComponent(cmpUpdate))
                .addContainerGap())
        );

        jButton1.setText("Donor Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Blood List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pblOrgInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 606, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(pnlCampaignInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCampaignInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pblOrgInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgSubmitButtonActionPerformed

         checkBoxUOrgUpdate.setVisible(true);
        if (checkBoxUOrgUpdate.isSelected()) {
            
            try{
               myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                String value1 = txtOrgID.getText();
                String value2 = txtOrgName.getText();
                String value3 = txtOrgAddress.getText();
                String value4 = txtOrgPhoneNo.getText();
                String value5 = txtOrgEmail.getText();
                
                String sql = "UPDATE `organization` SET `orgName`= '"+value2+"',`orgAddress`='"+value3+"',`orgPhoneNo`='"+value4+"',`orgEmail`='"+value5+"' WHERE id ='"+value1+"'";
                pst = myConn.prepareStatement(sql);
                
                pst.execute();
             
               
                JOptionPane.showMessageDialog(null,"Update");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
         
    }//GEN-LAST:event_btnOrgSubmitButtonActionPerformed

    private void checkBoxUOrgUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxUOrgUpdateActionPerformed
        if (checkBoxUOrgUpdate.isSelected()) {
            
            txtOrgName.setEditable(true);
            txtOrgAddress.setEditable(true);
            txtOrgPhoneNo.setEditable(true);
            txtOrgEmail.setEditable(true);
            //organization.updateDetails(txtOrgName.getText(), txtOrgAddress.getText(), txtOrgPhoneNo.getText(), txtOrgEmail.getText());
        } else {
           
            txtOrgName.setEditable(false);
            txtOrgAddress.setEditable(false);
            txtOrgPhoneNo.setEditable(false);
            txtOrgEmail.setEditable(false);
        }
    }//GEN-LAST:event_checkBoxUOrgUpdateActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int i = jTable2.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
    try {
        txtCamID.setText(model.getValueAt(i,0).toString());
        txtCampaignName.setText(model.getValueAt(i,1).toString());
        Date sdf = new SimpleDateFormat("dd-MM-yyyy").parse((String)model.getValueAt(i,2));
        jDateChooser1.setDate(sdf);
        txtCampainVenue.setText(model.getValueAt(i, 3).toString());
      
    
    } catch (ParseException ex) {
        Logger.getLogger(OrgMainPage.class.getName()).log(Level.SEVERE, null, ex);
    }
            
       
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void btnCampaignSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampaignSubmitButtonActionPerformed
        
        for (int i = countCampaign; i == countCampaign; i++) {
            SimpleDateFormat sdf =new SimpleDateFormat("dd-MM-yyyy", Locale.getDefault());
            String startDate=sdf.format(jDateChooser1.getDate());
            
            //            organization.setCampaign(campaign[i]);
            //            String campaignDetailString = (countCampaign + 1) + ")" + " " + campaign[i].getCampaignName() + "   |   " + campaign[i].getCampaignStartDate() + "   |   " +
            //                    campaign[i].getCampaignVenue() + "   |   " + organization.getOrgnizationName() + "<BR>";
            //            campaignDetail += campaignDetailString;
              if (!cmpUpdate.isSelected()) {
            try {
                myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                myStat = myConn.createStatement();
                myStat.execute("CREATE TABLE IF NOT EXISTS `phase3`.`campaign` ( `id` INT NOT NULL AUTO_INCREMENT , `campaignName` TEXT NOT NULL , `campaignStartDate` TEXT NOT NULL , `campaignVenue` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;");
                myStat.execute("SELECT * FROM `campaign`");
                myStat.execute("INSERT INTO `campaign` (`campaignName`, `campaignStartDate`, `campaignVenue`) VALUES('" + txtCampaignName.getText() + "','" +
                    startDate + "','" +txtCampainVenue.getText() + "');");
                //myRs = myStat.executeQuery("SELECT * FROM campaign INNER JOIN organization ON organization.orgName=campaign.orgName where id = '"+(i+1)+"'");
                myRs = myStat.executeQuery("SELECT * FROM campaign");
                String campaignDetailString = "";
                while (myRs.next()) {
                    campaignDetailString = myRs.getString("id") + ")" + " " + myRs.getString("campaignName") + "\n" + myRs.getString("campaignStartDate") + "\n" +
                    myRs.getString("campaignVenue") + "<BR>";
                    txtCampaignName.setEditable(false);
            jDateChooser1.setEnabled(false);
            txtCampainVenue.setEditable(false);

                }
                campaignDetail += campaignDetailString;
                DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
               model.setRowCount(0);
               showCamTable();
               JOptionPane.showMessageDialog(null,"Insert");
            } catch (SQLException e) {
                
            }
              }
            if (cmpUpdate.isSelected()) {
            try{
               myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                String value1 = txtCamID.getText();
                String value2 =txtCampaignName.getText();
                String value3 = startDate;
                String value4 = txtCampainVenue.getText();
                
                
                String sql = "UPDATE `campaign` SET `campaignName`='"+value2+"',`campaignStartDate`='"+value3+"',`campaignVenue`='"+value4+"' WHERE id ='"+value1+"'";
                pst = myConn.prepareStatement(sql);
                
                pst.execute();
                DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
               model.setRowCount(0);
                showCamTable();
               
                JOptionPane.showMessageDialog(null,"Update");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }

        }

        // lblCampaignArrayDetails.setText("<html>" + campaignDetail + "</html>");

        countCampaign++;
    }//GEN-LAST:event_btnCampaignSubmitButtonActionPerformed

    private void cmpUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpUpdateActionPerformed
        if (cmpUpdate.isSelected()) {
            txtCamID.setEditable(false);
            txtCampaignName.setEditable(true);
            jDateChooser1.setEnabled(true);
            txtCampainVenue.setEditable(true);

        } else {
            txtCamID.setEditable(false);
            txtCampaignName.setEditable(false);
            jDateChooser1.setEnabled(false);
            txtCampainVenue.setEditable(false);
        }
    }//GEN-LAST:event_cmpUpdateActionPerformed

    private void txtCamIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
            myStat = myConn.createStatement();
            String sql = "SELECT id FROM organization WHERE id=1";
            ResultSet rs = myStat.executeQuery(sql);
            while(rs.next()){
                int cmpID = rs.getInt("id");
                new DonorInformation(cmpID).setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
            myStat = myConn.createStatement();
            String sql = "SELECT id FROM organization WHERE id=1";
            ResultSet rs = myStat.executeQuery(sql);
            while(rs.next()){
                int cmpID = rs.getInt("id");
                new BloodList(cmpID).setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtOrgIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrgIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtOrgIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrgMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrgMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrgMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrgMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrgMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCampaignSubmitButton;
    private javax.swing.JButton btnOrgSubmitButton;
    private javax.swing.JCheckBox checkBoxUOrgUpdate;
    private javax.swing.JCheckBox cmpUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCampaignHeader;
    private javax.swing.JLabel lblCampaignName;
    private javax.swing.JLabel lblCampaignStartDate;
    private javax.swing.JLabel lblCampaignVenue;
    private javax.swing.JLabel lblOrgAddress;
    private javax.swing.JLabel lblOrgEmail;
    private javax.swing.JLabel lblOrgHeader;
    private javax.swing.JLabel lblOrgID1;
    private javax.swing.JLabel lblOrgID2;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblOrgPhoneNo;
    private javax.swing.JPanel pblOrgInput;
    private javax.swing.JPanel pnlCampaignInput;
    private javax.swing.JTextField txtCamID;
    private javax.swing.JTextField txtCampaignName;
    private javax.swing.JTextField txtCampainVenue;
    private javax.swing.JTextField txtOrgAddress;
    private javax.swing.JTextField txtOrgEmail;
    private javax.swing.JTextField txtOrgID;
    public javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgPhoneNo;
    // End of variables declaration//GEN-END:variables
}
